# Generated by Django 6.0.8 on 2026-09-06 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gridy_auth', '0009_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='purok',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
