# Generated by Django 6.0.8 on 2026-09-06 13:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gridy_auth', '0010_alter_resident_purok'),
        ('gridy_services', '0009_documentrequest_purpose'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='documentrequest',
            name='barangay',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_requests', to='gridy_auth.barangay'),
        ),
        migrations.AddField(
            model_name='documentrequest',
            name='fee_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Clearance issuance fee in PHP', max_digits=8),
        ),
        migrations.AddField(
            model_name='documentrequest',
            name='is_walkin',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='documentrequest',
            name='or_number',
            field=models.CharField(blank=True, help_text='Official Receipt Number issued by Barangay Treasurer', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='documentrequest',
            name='walkin_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='documentrequest',
            name='walkin_purok',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='documentrequest',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='documentrequest',
            index=models.Index(fields=['barangay', 'status'], name='gridy_servi_baranga_528d78_idx'),
        ),
    ]
